### ISSUE TITLE
HTTPSTATUS Indicator bugs out CSS and shoves logo over to the left.

### ISSUE THREAD

**Issue by Phoenixthedoggo** [rmountjoy92/DashMachine#118]
When configuring a HTTPSTATUS on a card, it pushes the logo of that card far left instead of using a z-index to have them in the same spot.

![image](https://user-images.githubusercontent.com/20131900/78822275-6ede1d80-79a0-11ea-9695-77cbc12837a7.png)

Not sure how to fix that, but doesn't look nice. :c

**Comment by marcjmiller** [comment]
Judging by the implementation, this seems like the intended behavior, to display the dot on the card corner rather than the app icon corner.  The submitted PR [#120] moves the icon as pictured below.
Is this more like what you want?
![image](https://user-images.githubusercontent.com/48929970/78861503-e775c600-7a02-11ea-96cf-e408e1cf7f28.png)

**Comment by marcjmiller** [comment]
This is a pretty dirty fix, the real fix would be a big change to how the cards are rendering data_sources as a whole.  Right now, they're forced into a second div element with left-align, and each data_source ends up in a new paragraph element per the code here: https://github.com/rmountjoy92/DashMachine/blob/a01a7b911e0800f6b65e81f7c088531f5d3912d4/dashmachine/templates/main/macros.html#L17-L39

**Comment by Phoenixthedoggo** [comment]
> Judging by the implementation, this seems like the intended behavior, to display the dot on the card corner rather than the app icon corner. The submitted PR [#120] moves the icon as pictured below, though the app icon still gets offset due to the second div in the card-content.
> Is this more like what you want?
> ![image](https://user-images.githubusercontent.com/48929970/78861503-e775c600-7a02-11ea-96cf-e408e1cf7f28.png)
> 
> ![image](https://user-images.githubusercontent.com/48929970/78861797-c1045a80-7a03-11ea-98d0-b9102be79b85.png)

Yea, that's more like what I was imagining, I just thought it looked really odd having it push over my icons. 🤔

**Comment by marcjmiller** [comment]
Yeah I honestly didn't even think about it when I was using it, but I like it closer to the icon rather than what it defaults to.  The PR I submitted only fixes half the issue, but it was too late for me to continue banging away at my least favorite part of being a web developer... CSS.

**Comment by rmountjoy92** [comment]
For app cards data sources work as follows:
- when there is no data source, an app card looks like this:
![image](https://user-images.githubusercontent.com/34513134/79074770-39954080-7cbc-11ea-8656-ec9a56894649.png)
- when you add a data source, the icon shifts over to allow space for the data source container (red):
![image](https://user-images.githubusercontent.com/34513134/79074803-5f224a00-7cbc-11ea-8bac-8adb8a309ed3.png)
- the data source appends html into that container. Whatever is configured in the data source will be appended to that container.

In the case of HTTPSTATUS, it's simply appending a right aligned bullet point:
![image](https://user-images.githubusercontent.com/34513134/79074925-47979100-7cbd-11ea-8d25-2983ac54ea88.png)

If there are multiple data sources on a card, they are not guaranteed to work well together, as they are just appended in one by one. Which is why you can modify the value_template of most data sources to include and changes needed for formatting (e.g. adding a `<br>` or some css or something)

With custom cards, you have a lot more freedom, because the data source container is the entire card: 
![image](https://user-images.githubusercontent.com/34513134/79075042-3307c880-7cbe-11ea-9c6f-64a031da9a90.png)


Check out the weather data source example to see how this is done. 
https://github.com/rmountjoy92/DashMachine/blob/master/dashmachine/platform/weather.py
