### ISSUE TITLE
Changing size of tiles

### ISSUE THREAD

**Issue by j-porsche** [rmountjoy92/DashMachine#15]
I really like your project and I want to use it. But I have many links so it could be a problem because you have to scroll a lot. I think it would be very nice to have an option to resize your tiles. 
Thank You!

**Comment by rmountjoy92** [comment]
Hello, thank you for the suggestion. There's a few reasons why this won't work. 
1. It would be nearly impossible for someone making a data source platform to format the data to look nice on cards when they have no idea what size the user's cards are. 
2. It would require a pretty much full rewrite of the home page. 
3. I've already implemented list view (which solves your problem of scrolling- there's also tags and search!)

I also plan on adding a 'dividers' feature that will give the option to display headers/dividers in between groups of tagged apps.

**Comment by j-porsche** [comment]
Okay I understand the problem. Maybe it is possible the add a second row to the list view? :)

**Comment by the4ndy** [comment]
> 1. It would be nearly impossible for someone making a data source platform to format the data to look nice on cards when they have no idea what size the user's cards are.

I think the template creators would define the "default" size of the card, and any changes the user has to deal with.

> 2. It would require a pretty much full rewrite of the home page.

I suspect this is due to grid view type stuff (im no expert sorry), but perhaps assigning a set max card size, and centering any smaller cards vertically and horizontally in that grid space would work....thus not requiring too much code rewriting

> 3. I've already implemented list view (which solves your problem of scrolling- there's also tags and search!)

I am assuming you mean "Collections"? If so, those are, in my opinion, kind of unusable. If you have scrolling set too high on your mouse, its too hard to scroll accurately in such a small view port.


> I also plan on adding a 'dividers' feature that will give the option to display headers/dividers in between groups of tagged apps.

This is a MUCH better way to deal with collections of items, but it still doesnt address the problem that with predefined card sizes and NO flexibility in the slightest, you are limited greatly by what you can and cannot display as a data_source for that app (the weather card is a PERFECT example, having to scroll for that info is counter intuitive to the whole idea of "links with info at a glance".  
  
Anyway, just my thoughts, i don't have the skills to make something as amazing as this project, i doubt i even have the skills to contribute (though i am keeping track of any of the hacky changes i make to hopefully provide some useful code one day), so i understand that this may come across as complaining, i do not intend that, i simply want to encourage you / inspire some potential options that may have been overlooked
